nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_credentials: false
        allow_headers: ['Content-Type', 'Accept', 'Authorization']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
        expose_headers: []
        max_age: 3600
        hosts: []
        origin_regex: false
        forced_allow_origin_value: null
