# run application tests with phpunit
name: PHPUnit Tests

on:
  push:
    branches:
      - main
      - dev

jobs:
  phpunit:
    name: Run PHPUnit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # setup php interpreter
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: intl

      # composer install
      - name: Install dependencies
        run: composer install --no-interaction --no-progress --no-suggest

      # phpunit process
      - name: Run PHPUnit
        run: php ./bin/phpunit
